- 모든 코드가 시간 초과가 났습니다... 해결법을 제시해주실 분을 구합니다...

In [20]:
##### 계수 정렬 알고리즘 #####
# 연속된 숫자가 아닌 1, 2, 3 그리고 갑자기 100이 나온다면 그 빈 공간에 해당하는 공간(메모리) 낭비가 생겨서 계수보다는 퀵이나 병합을 많이 사용함

N = int(input())
n = []

for i in range(N):
    a = int(input())
    n.append(a)

output = [0] * (max(n)+1)           # 계수 정렬을 위한 출력 배열 만들기. np.zeros를 쓸 수 없어서 이렇게 만듦! # 출력 배열은 입력 배열보다 많아야 하므로 +1을 해줌

for i in range(N):                  # 지금은 range(N) = len(n) 이라 이렇게 쓰지만 여러 경우에도 적용하고 싶다면 len(n)을 쓰는 게 맞음
    output[n[i]] + 1                # 입력 배열과 동일한 출력 배열의 인덱스에 +1을 해줌. # 만약 [5, 4, 5, 3, 2, 1] 라고 한다면 출력 배열에는 [0, 1, 1, 1, 1, 2]로 입력 됨

for i in range(len(output)):        # i에 range(5) = 0~5를 for문으로 돌림
    for j in range(output[i]):      # 출력 배열을 불러와서 각 인덱스에 몇 개의 값이 들어가있는지 확인 및 아래에서 출력
        print(i)

5
5
4
3
2
2
3
4
5
5

In [8]:
##### 퀵 정렬 알고리즘 #####

N = int(input())
n = []

for i in range(N):
    a = int(input())
    n.append(a)

def quick(array, start, end):
    if start >= end:
        return
    min = start
    left = start+1
    right = end
    while left <= right:
        while left <= end and array[left] <= array[min]:
            left += 1
        while right > start and array[right] >= array[min]:
            right -= 1
        if left > right:
            array[right], array[min] = array[min], array[right]
        else:
            array[left], array[min] = array[min], array[left]
    
    quick(array, start, right-1)
    quick(array, right+1, end)

quick(n, 0, len(n)-1)

for i in n:
    print(i)

5
5
4
3
2
1
1
2
3
4
5

In [22]:
##### 병합 정렬 알고리즘 #####

def merge(array):
    n = len(array)

    if n <= 1:
        return array
    
    benchmark = n // 2
    
    group1 = merge(array[:benchmark])
    group2 = merge(array[benchmark:])

    result = []

    while group1 and group2:
        if group1[0] < group2[0]:
            result.append(group1.pop(0))
        else:
            result.append(group2.pop(0))
    while group1:
        result.append(group1.pop(0))
    while group2:
        result.append(group2.pop(0))
    return result

N = int(input())
n = []

for i in range(N):
    a = int(input())
    n.append(a)

for i in merge(n):
    print(i)

5
5
4
3
2
1
1
2
3
4
5